version: 1.0.{build}
configuration: Release
image: Visual Studio 2019
platform: Any CPU
before_build:
- cmd: >-
    mkdir packages

    cd HelloSign

    nuget install -o ..\packages

    cd ..
build:
  project: HelloSign\HelloSign.csproj
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: HEznQoAx4Mjm60b8LDlG8skghbry32Aemt4gEE3qXjXynJWfmER3RlWZVqbl19tn
  skip_symbols: true
  on:
    branch: v3
    APPVEYOR_REPO_TAG: true