/*
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HelloSign.Client.OpenAPIDateConverter;

namespace HelloSign.Model
{
    /// <summary>
    /// ApiAppGetResponse
    /// </summary>
    [DataContract(Name = "ApiAppGetResponse")]
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public partial class ApiAppGetResponse : IOpenApiTyped, IEquatable<ApiAppGetResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiAppGetResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiAppGetResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiAppGetResponse" /> class.
        /// </summary>
        /// <param name="apiApp">apiApp.</param>
        /// <param name="warnings">A list of warnings..</param>
        public ApiAppGetResponse(ApiAppResponse apiApp = default(ApiAppResponse), List<WarningResponse> warnings = default(List<WarningResponse>))
        {
            
            this.ApiApp = apiApp;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Gets or Sets ApiApp
        /// </summary>
        [DataMember(Name = "api_app", EmitDefaultValue = true)]
        public ApiAppResponse ApiApp { get; set; }

        /// <summary>
        /// A list of warnings.
        /// </summary>
        /// <value>A list of warnings.</value>
        [DataMember(Name = "warnings", EmitDefaultValue = true)]
        public List<WarningResponse> Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiAppGetResponse {\n");
            sb.Append("  ApiApp: ").Append(ApiApp).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiAppGetResponse);
        }

        /// <summary>
        /// Returns true if ApiAppGetResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiAppGetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiAppGetResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ApiApp == input.ApiApp ||
                    (this.ApiApp != null &&
                    this.ApiApp.Equals(input.ApiApp))
                ) && 
                (
                    this.Warnings == input.Warnings ||
                    this.Warnings != null &&
                    input.Warnings != null &&
                    this.Warnings.SequenceEqual(input.Warnings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApiApp != null)
                {
                    hashCode = (hashCode * 59) + this.ApiApp.GetHashCode();
                }
                if (this.Warnings != null)
                {
                    hashCode = (hashCode * 59) + this.Warnings.GetHashCode();
                }
                return hashCode;
            }
        }

        public List<OpenApiType> GetOpenApiTypes()
        {
            var types = new List<OpenApiType>();
            types.Add(new OpenApiType(){
                Name = "api_app",
                Property = "ApiApp",
                Type = "ApiAppResponse",
                Value = ApiApp,
            });
            types.Add(new OpenApiType(){
                Name = "warnings",
                Property = "Warnings",
                Type = "List<WarningResponse>",
                Value = Warnings,
            });

            return types;
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
