/*
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HelloSign.Client.OpenAPIDateConverter;

namespace HelloSign.Model
{
    /// <summary>
    /// EventCallbackRequest
    /// </summary>
    [DataContract(Name = "EventCallbackRequest")]
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public partial class EventCallbackRequest : IOpenApiTyped, IEquatable<EventCallbackRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventCallbackRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventCallbackRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventCallbackRequest" /> class.
        /// </summary>
        /// <param name="_event">_event (required).</param>
        /// <param name="account">account.</param>
        /// <param name="signatureRequest">signatureRequest.</param>
        /// <param name="template">template.</param>
        public EventCallbackRequest(EventCallbackRequestEvent _event = default(EventCallbackRequestEvent), AccountResponse account = default(AccountResponse), SignatureRequestResponse signatureRequest = default(SignatureRequestResponse), TemplateResponse template = default(TemplateResponse))
        {
            
            // to ensure "_event" is required (not null)
            if (_event == null)
            {
                throw new ArgumentNullException("_event is a required property for EventCallbackRequest and cannot be null");
            }
            this.Event = _event;
            this.Account = account;
            this.SignatureRequest = signatureRequest;
            this.Template = template;
        }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public EventCallbackRequestEvent Event { get; set; }

        /// <summary>
        /// Gets or Sets Account
        /// </summary>
        [DataMember(Name = "account", EmitDefaultValue = true)]
        public AccountResponse Account { get; set; }

        /// <summary>
        /// Gets or Sets SignatureRequest
        /// </summary>
        [DataMember(Name = "signature_request", EmitDefaultValue = true)]
        public SignatureRequestResponse SignatureRequest { get; set; }

        /// <summary>
        /// Gets or Sets Template
        /// </summary>
        [DataMember(Name = "template", EmitDefaultValue = true)]
        public TemplateResponse Template { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventCallbackRequest {\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  SignatureRequest: ").Append(SignatureRequest).Append("\n");
            sb.Append("  Template: ").Append(Template).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EventCallbackRequest);
        }

        /// <summary>
        /// Returns true if EventCallbackRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of EventCallbackRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventCallbackRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Event == input.Event ||
                    (this.Event != null &&
                    this.Event.Equals(input.Event))
                ) && 
                (
                    this.Account == input.Account ||
                    (this.Account != null &&
                    this.Account.Equals(input.Account))
                ) && 
                (
                    this.SignatureRequest == input.SignatureRequest ||
                    (this.SignatureRequest != null &&
                    this.SignatureRequest.Equals(input.SignatureRequest))
                ) && 
                (
                    this.Template == input.Template ||
                    (this.Template != null &&
                    this.Template.Equals(input.Template))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Event != null)
                {
                    hashCode = (hashCode * 59) + this.Event.GetHashCode();
                }
                if (this.Account != null)
                {
                    hashCode = (hashCode * 59) + this.Account.GetHashCode();
                }
                if (this.SignatureRequest != null)
                {
                    hashCode = (hashCode * 59) + this.SignatureRequest.GetHashCode();
                }
                if (this.Template != null)
                {
                    hashCode = (hashCode * 59) + this.Template.GetHashCode();
                }
                return hashCode;
            }
        }

        public List<OpenApiType> GetOpenApiTypes()
        {
            var types = new List<OpenApiType>();
            types.Add(new OpenApiType(){
                Name = "event",
                Property = "Event",
                Type = "EventCallbackRequestEvent",
                Value = Event,
            });
            types.Add(new OpenApiType(){
                Name = "account",
                Property = "Account",
                Type = "AccountResponse",
                Value = Account,
            });
            types.Add(new OpenApiType(){
                Name = "signature_request",
                Property = "SignatureRequest",
                Type = "SignatureRequestResponse",
                Value = SignatureRequest,
            });
            types.Add(new OpenApiType(){
                Name = "template",
                Property = "Template",
                Type = "TemplateResponse",
                Value = Template,
            });

            return types;
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
