/*
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HelloSign.Client.OpenAPIDateConverter;

namespace HelloSign.Model
{
    /// <summary>
    /// ReportCreateRequest
    /// </summary>
    [DataContract(Name = "ReportCreateRequest")]
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public partial class ReportCreateRequest : IOpenApiTyped, IEquatable<ReportCreateRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines ReportType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReportTypeEnum
        {
            /// <summary>
            /// Enum UserActivity for value: user_activity
            /// </summary>
            [EnumMember(Value = "user_activity")]
            UserActivity = 1,

            /// <summary>
            /// Enum DocumentStatus for value: document_status
            /// </summary>
            [EnumMember(Value = "document_status")]
            DocumentStatus = 2

        }



        /// <summary>
        /// The type(s) of the report you are requesting. Allowed values are &#x60;user_activity&#x60; and &#x60;document_status&#x60;. User activity reports contain list of all users and their activity during the specified date range. Document status report contain a list of signature requests created in the specified time range (and their status).
        /// </summary>
        /// <value>The type(s) of the report you are requesting. Allowed values are &#x60;user_activity&#x60; and &#x60;document_status&#x60;. User activity reports contain list of all users and their activity during the specified date range. Document status report contain a list of signature requests created in the specified time range (and their status).</value>
        [DataMember(Name = "report_type", IsRequired = true, EmitDefaultValue = true)]
        public List<ReportTypeEnum> ReportType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportCreateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReportCreateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportCreateRequest" /> class.
        /// </summary>
        /// <param name="endDate">The (inclusive) end date for the report data in &#x60;MM/DD/YYYY&#x60; format. (required).</param>
        /// <param name="reportType">The type(s) of the report you are requesting. Allowed values are &#x60;user_activity&#x60; and &#x60;document_status&#x60;. User activity reports contain list of all users and their activity during the specified date range. Document status report contain a list of signature requests created in the specified time range (and their status). (required).</param>
        /// <param name="startDate">The (inclusive) start date for the report data in &#x60;MM/DD/YYYY&#x60; format. (required).</param>
        public ReportCreateRequest(string endDate = default(string), List<ReportTypeEnum> reportType = default(List<ReportTypeEnum>), string startDate = default(string))
        {
            
            // to ensure "endDate" is required (not null)
            if (endDate == null)
            {
                throw new ArgumentNullException("endDate is a required property for ReportCreateRequest and cannot be null");
            }
            this.EndDate = endDate;
            // to ensure "reportType" is required (not null)
            if (reportType == null)
            {
                throw new ArgumentNullException("reportType is a required property for ReportCreateRequest and cannot be null");
            }
            this.ReportType = reportType;
            // to ensure "startDate" is required (not null)
            if (startDate == null)
            {
                throw new ArgumentNullException("startDate is a required property for ReportCreateRequest and cannot be null");
            }
            this.StartDate = startDate;
        }

        /// <summary>
        /// The (inclusive) end date for the report data in &#x60;MM/DD/YYYY&#x60; format.
        /// </summary>
        /// <value>The (inclusive) end date for the report data in &#x60;MM/DD/YYYY&#x60; format.</value>
        [DataMember(Name = "end_date", IsRequired = true, EmitDefaultValue = true)]
        public string EndDate { get; set; }

        /// <summary>
        /// The (inclusive) start date for the report data in &#x60;MM/DD/YYYY&#x60; format.
        /// </summary>
        /// <value>The (inclusive) start date for the report data in &#x60;MM/DD/YYYY&#x60; format.</value>
        [DataMember(Name = "start_date", IsRequired = true, EmitDefaultValue = true)]
        public string StartDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReportCreateRequest {\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  ReportType: ").Append(ReportType).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReportCreateRequest);
        }

        /// <summary>
        /// Returns true if ReportCreateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ReportCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReportCreateRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.EndDate == input.EndDate ||
                    (this.EndDate != null &&
                    this.EndDate.Equals(input.EndDate))
                ) && 
                (
                    this.ReportType == input.ReportType ||
                    this.ReportType.SequenceEqual(input.ReportType)
                ) && 
                (
                    this.StartDate == input.StartDate ||
                    (this.StartDate != null &&
                    this.StartDate.Equals(input.StartDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EndDate != null)
                {
                    hashCode = (hashCode * 59) + this.EndDate.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ReportType.GetHashCode();
                if (this.StartDate != null)
                {
                    hashCode = (hashCode * 59) + this.StartDate.GetHashCode();
                }
                return hashCode;
            }
        }

        public List<OpenApiType> GetOpenApiTypes()
        {
            var types = new List<OpenApiType>();
            types.Add(new OpenApiType(){
                Name = "end_date",
                Property = "EndDate",
                Type = "string",
                Value = EndDate,
            });
            types.Add(new OpenApiType(){
                Name = "report_type",
                Property = "ReportType",
                Type = "List<string>",
                Value = ReportType,
            });
            types.Add(new OpenApiType(){
                Name = "start_date",
                Property = "StartDate",
                Type = "string",
                Value = StartDate,
            });

            return types;
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
