/*
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HelloSign.Client.OpenAPIDateConverter;

namespace HelloSign.Model
{
    /// <summary>
    /// TeamInvitesResponse
    /// </summary>
    [DataContract(Name = "TeamInvitesResponse")]
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public partial class TeamInvitesResponse : IOpenApiTyped, IEquatable<TeamInvitesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamInvitesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TeamInvitesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamInvitesResponse" /> class.
        /// </summary>
        /// <param name="teamInvites">Contains a list of team invites and their roles..</param>
        /// <param name="warnings">warnings.</param>
        public TeamInvitesResponse(List<TeamInviteResponse> teamInvites = default(List<TeamInviteResponse>), List<WarningResponse> warnings = default(List<WarningResponse>))
        {
            
            this.TeamInvites = teamInvites;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Contains a list of team invites and their roles.
        /// </summary>
        /// <value>Contains a list of team invites and their roles.</value>
        [DataMember(Name = "team_invites", EmitDefaultValue = true)]
        public List<TeamInviteResponse> TeamInvites { get; set; }

        /// <summary>
        /// Gets or Sets Warnings
        /// </summary>
        [DataMember(Name = "warnings", EmitDefaultValue = true)]
        public List<WarningResponse> Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TeamInvitesResponse {\n");
            sb.Append("  TeamInvites: ").Append(TeamInvites).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TeamInvitesResponse);
        }

        /// <summary>
        /// Returns true if TeamInvitesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TeamInvitesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TeamInvitesResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TeamInvites == input.TeamInvites ||
                    this.TeamInvites != null &&
                    input.TeamInvites != null &&
                    this.TeamInvites.SequenceEqual(input.TeamInvites)
                ) && 
                (
                    this.Warnings == input.Warnings ||
                    this.Warnings != null &&
                    input.Warnings != null &&
                    this.Warnings.SequenceEqual(input.Warnings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TeamInvites != null)
                {
                    hashCode = (hashCode * 59) + this.TeamInvites.GetHashCode();
                }
                if (this.Warnings != null)
                {
                    hashCode = (hashCode * 59) + this.Warnings.GetHashCode();
                }
                return hashCode;
            }
        }

        public List<OpenApiType> GetOpenApiTypes()
        {
            var types = new List<OpenApiType>();
            types.Add(new OpenApiType(){
                Name = "team_invites",
                Property = "TeamInvites",
                Type = "List<TeamInviteResponse>",
                Value = TeamInvites,
            });
            types.Add(new OpenApiType(){
                Name = "warnings",
                Property = "Warnings",
                Type = "List<WarningResponse>",
                Value = Warnings,
            });

            return types;
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
